-- Task 2: Identity, RBAC, and Location foundation.
--
-- This migration was authored by hand rather than generated by
-- `prisma migrate dev`, because the Prisma CLI's schema-engine binary could
-- not be downloaded in the environment this was written in (network egress
-- to binaries.prisma.sh was blocked). It mirrors exactly what Prisma would
-- generate from prisma/schema.prisma, plus the manual PostGIS additions
-- called out below. It has been applied and verified against a real local
-- PostgreSQL 16 + PostGIS 3.4 instance — see prisma/README.md for details
-- and for what still needs re-verification once `prisma migrate dev` can
-- run against this migration in a normal environment.

-- CreateExtension
-- Not generated via Prisma's postgresqlExtensions preview feature (that
-- feature is being discontinued upstream) — created directly here instead,
-- per the plan to use raw SQL for anything PostGIS-related.
CREATE EXTENSION IF NOT EXISTS postgis;

-- CreateEnum
CREATE TYPE "UserStatus" AS ENUM ('active', 'suspended', 'pending_verification');

-- CreateEnum
CREATE TYPE "LocationLevel" AS ENUM ('country', 'region', 'zone', 'city', 'subcity', 'woreda', 'kebele', 'neighborhood');

-- CreateTable
CREATE TABLE "users" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "email" TEXT NOT NULL,
    "phone" TEXT,
    "password_hash" TEXT,
    "full_name" TEXT NOT NULL,
    "status" "UserStatus" NOT NULL DEFAULT 'pending_verification',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "roles" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" TEXT NOT NULL,
    "description" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "roles_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "permissions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "key" TEXT NOT NULL,
    "description" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "permissions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "role_permissions" (
    "role_id" UUID NOT NULL,
    "permission_id" UUID NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "role_permissions_pkey" PRIMARY KEY ("role_id","permission_id")
);

-- CreateTable
CREATE TABLE "user_roles" (
    "user_id" UUID NOT NULL,
    "role_id" UUID NOT NULL,
    "assigned_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "user_roles_pkey" PRIMARY KEY ("user_id","role_id")
);

-- CreateTable
CREATE TABLE "location_nodes" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "parent_id" UUID,
    "level" "LocationLevel" NOT NULL,
    "name" TEXT NOT NULL,
    "name_amharic" TEXT,
    "slug" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "location_nodes_pkey" PRIMARY KEY ("id")
);

-- AddColumn
-- Prisma's `Unsupported(...)` fields are not created by `prisma migrate dev`
-- automatically pre-generation; the column is added explicitly here, per the
-- plan to handle all PostGIS geometry/geography columns via raw SQL.
ALTER TABLE "location_nodes" ADD COLUMN "boundary" geometry(Polygon, 4326);

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- CreateIndex
CREATE UNIQUE INDEX "users_phone_key" ON "users"("phone");

-- CreateIndex
CREATE UNIQUE INDEX "roles_name_key" ON "roles"("name");

-- CreateIndex
CREATE UNIQUE INDEX "permissions_key_key" ON "permissions"("key");

-- CreateIndex
CREATE INDEX "role_permissions_permission_id_idx" ON "role_permissions"("permission_id");

-- CreateIndex
CREATE INDEX "user_roles_role_id_idx" ON "user_roles"("role_id");

-- CreateIndex
CREATE UNIQUE INDEX "location_nodes_slug_key" ON "location_nodes"("slug");

-- CreateIndex
CREATE INDEX "location_nodes_parent_id_idx" ON "location_nodes"("parent_id");

-- CreateIndex
CREATE INDEX "location_nodes_level_idx" ON "location_nodes"("level");

-- CreateIndex
-- Spatial (GIST) index on the PostGIS geometry column. Not a Prisma-native
-- index type declaration — created directly via raw SQL, per the plan.
CREATE INDEX "location_nodes_boundary_gist_idx" ON "location_nodes" USING GIST ("boundary");

-- AddForeignKey
ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_permission_id_fkey" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "user_roles" ADD CONSTRAINT "user_roles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
-- Restrict, not Cascade: a role that is still assigned to users cannot be
-- deleted out from under them. Users must be reassigned first.
ALTER TABLE "user_roles" ADD CONSTRAINT "user_roles_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
-- Restrict, not Cascade: a location node with existing children cannot be
-- deleted until its children are reassigned or removed. Prevents silently
-- orphaning part of the location hierarchy.
ALTER TABLE "location_nodes" ADD CONSTRAINT "location_nodes_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "location_nodes"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
